nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
yarnPath: .yarn/releases/yarn-classic.cjs
