/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _TEMPLATE: typeof import('./src/components/_TEMPLATE.vue')['default']
    AboutPicture: typeof import('./src/components/AboutPicture.vue')['default']
    AboutText: typeof import('./src/components/AboutText.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    CounterButton: typeof import('./src/components/CounterButton.vue')['default']
    FooterContent: typeof import('./src/components/FooterContent.vue')['default']
    GenderText: typeof import('./src/components/GenderText.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainText: typeof import('./src/components/MainText.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    NavItemURL: typeof import('./src/components/NavItemURL.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
