[env]
DAVE_IO_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
'aqua:caddyserver/caddy' = { version = '2.10.0' }
node = { version = 'lts' }                        # Supports Cloudflare Workers
bun = { version = '1.2.13' }
