#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2025-02-23"
name = "dave-io"
pages_build_output_dir = "dist"

[placement]
mode = "smart"

[assets]
directory = "./public/"
binding = "PUBLIC"
