#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2025-04-23"
name = "dave-io"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"
