# extends:
# - stylelint-config-standard
# - stylelint-config-standard-scss
# - postcss
# - postcss-scss
# - stylelint-config-tailwindcss
rules:
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
