name: gar
on:
  push:
    tags:
      - v*
env:
  FULL_IMAGE_NAME: ${{ vars.REGISTRY }}/${{ vars.PROJECT }}/${{ vars.REPO }}/${{ vars.IMAGE_NAME }}
permissions:
  contents: read
  attestations: write
  id-token: write
jobs:
  gar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4.2.2
      - name: auth
        id: auth
        uses: google-github-actions/auth@v2.1.8
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s
      - name: login
        id: login
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: oauth2accesstoken
          password: ${{steps.auth.outputs.access_token}}
      - name: meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
      - name: push
        id: push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: attestation
        id: attestation
        uses: actions/attest-build-provenance@v2.2.3
        with:
          subject-name: ${{ env.FULL_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
